name = "chatgpt-parser"
compatibility_date = "2024-01-01"

[build]
command = "npm run pages:build"
cwd = "."

[build.environment_variables]
NODE_VERSION = "18"

[[pages.functions]]
name = "parse-conversation"
path = "/api/parse-conversation"

[[pages.functions]]
name = "generate-pdf"
path = "/api/generate-pdf"
